export const CREATED_STATUS = 201
export const SERVER_ERROR_STATUS = 500
export const INVALID_REQUEST_STATUS = 400

export default {
  CREATED_STATUS,
  SERVER_ERROR_STATUS,
  INVALID_REQUEST_STATUS
}